default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres

development:
  primary:
    <<: *default
    database: banco_cinema
  cache:
    <<: *default
    database: cinema_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: cinema_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: cinema_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: cinema_test

production:
  primary: &primary_production
    <<: *default
    database: banco_cinema
    username: postgres
    password: <%= ENV["CINEMA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cinema_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cinema_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cinema_production_cable
    migrations_paths: db/cable_migrate